version: 2

sources:
  - name: raw_energy
    schema: energy_market_france
    tables:
      - name: raw_energy_market_france

  - name: raw_performance
    schema: energy_data
    tables:
      - name: energy_reports

models:
  - name: stg_energy_market_france
    description: "Energy (MW) consumption and topology"
    config:
      elementary:
        timestamp_column: t
    columns:
      - name: t
        description: "Timestamp, the primary key for this table (by 15 minutes increments)"
        data_tests:
          - unique
          - not_null
      - name: actual
        description: "The effective energy consumption for the period"
        tests:
          - elementary.column_anomalies:
              column_anomalies:
                - min
                - max
                - average
                - standard_deviation
                - variance
      - name: estimated_d1
        description: "Previous day estimated energy consumption for the period"
      - name: estimated_d
        description: "Day estimated energy consumption for the period"

      - name: co2_ratio
        description: "Energy (kWh) to CO2 (gram) ratio for the period"

      - name: fuel_oil
        description: "Amount of Fuel based energy consumed for the period"
      - name: coal
        description: "Amount of Coal based energy consumed for the period"
      - name: gas
        description: "Amount of Gas based energy consumed for the period"
      - name: nuclear
        description: "Amount of Nuclear based energy consumed for the period"
      - name: wind
        description: "Amount of Wind based energy consumed for the period"
      - name: solar
        description: "Amount of Solar based energy consumed for the period"
      - name: hydropower
        description: "Amount of Hydropower based energy consumed for the period"
      - name: pumped_storage
        description: "Amount of Pumped Storage based energy consumed for the period"
      - name: bioenergy
        description: "Amount of Bioenergy based energy consumed for the period"

      - name: import_england
        description: "Amount of energy imported from England (half hourly data, negative means export)"
      - name: import_spain
        description: "Amount of energy imported from Spain (half hourly data, negative means export)"
      - name: import_italy
        description: "Amount of energy imported from Italy (half hourly data, negative means export)"
      - name: import_swiss
        description: "Amount of energy imported from Switzerland (half hourly data, negative means export)"
      - name: import_germany_belgium
        description: "Amount of energy imported from Germany and Belgium (half hourly data, negative means export)"
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies

models:
  - name: stg_energy_reports
    description: "Energy Performance Certificates"
    columns:
      - name: id
        description: "Establishment number"
        data_tests:
          - unique
          - not_null
      - name: report_date
        description: "Establishment date"
        data_tests:
          - not_null
      - name: ges_label
        description: "GES (https://promee.fr/renovation-energetique/quest-ce-que-la-classe-ges-comment-est-elle-calculee) Label"
        data_tests:
          - not_null
      - name: dpe_label
        description: "DPE (https://www.ecologie.gouv.fr/politiques-publiques/diagnostic-performance-energetique-dpe) Label"
        data_tests:
          - not_null
      - name: building_year
        description: "Year the building was constructed"
      - name: postal_code
        description: "Location postal code"
        data_tests:
          - not_null
      - name: building_position
        description: "Location within the building (RDC, top floor, in between)"
      - name: construction_period
        description: "Period the building was constructed"
        data_tests:
          - not_null
