
version: 2

models:
  - name: fact_energy_usage_france
    description: "Energy (MW) consumption over time"
    columns:
      - name: timestamp_hour
        description: "Timestamp hour, the primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: usage
        description: "The effective energy consumption for the period"
        data_tests:
          - not_null
      - name: usage_min
        description: "The minimum energy consumption for the period"
        data_tests:
          - not_null
      - name: usage_max
        description: "The maximum energy consumption for the period"
        data_tests:
          - not_null
      - name: usage_average
        description: "The average energy consumption for the period"
        data_tests:
          - not_null
      - name: co2_impact
        description: "The co2 (gram) impact for the period total energy consumption"
        data_tests:
          - not_null
      - name: usage_renewable
        description: "The effective renewable energy consumption for the period"
        data_tests:
          - not_null
      - name: usage_non_renewable
        description: "The effective non renewable energy consumption for the period"
        data_tests:
          - not_null
      - name: import_england
        description: "Amount of energy imported from England for the period" (negative means export)"
        data_tests:
          - not_null
      - name: import_spain
        description: "Amount of energy imported from Spain for the period" (negative means export)"
        data_tests:
          - not_null
      - name: import_italy
        description: "Amount of energy imported from Italy for the period" (negative means export)"
        data_tests:
          - not_null
      - name: import_germany_belgium
        description: "Amount of energy imported from Germany and Belgium for the period" (negative means export)"
        data_tests:
          - not_null

  - name: fact_energy_usage_over_week
    description: "Energy (MW) consumption over week (day and hour), broken down per year and month"
    columns:
      - name: timestamp_month
        description: "Timestamp of the beginning of the month"
        data_tests:
          - not_null
      - name: year
        description: "Year as integer"
        data_tests:
          - not_null
      - name: month
        description: "Month as integer"
        data_tests:
          - not_null
      - name: day_of_week
        description: "Day of week as integer (0 -> Sunday)"
        data_tests:
          - not_null
      - name: hour
        description: "Hour as integer"
        data_tests:
          - not_null
      - name: usage
        description: "The average energy consumption for the period"
