name: Refresh Data Pipeline

on:
  workflow_dispatch:

jobs:
  refresh_data:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Trigger ingestion Lambda
        run: |
          aws lambda invoke \
            --function-name energy-market-france-ingestion \
            --region eu-north-1 \
            output.json
          echo "Triggered ingestion Lambda."

      - name: Monitor upsert Lambda logs for completion
        run: |
          LOG_GROUP_NAME="/aws/lambda/energy-market-france-upsert"
          START_TIME=$(date +%s000)  # Current time in milliseconds
          echo "Monitoring logs from $LOG_GROUP_NAME starting at $START_TIME..."

          COMPLETION_MESSAGE="Data load complete"  # Define the message that indicates completion
          TIMEOUT=900  # Timeout in seconds (15 minutes)
          POLL_INTERVAL=30  # Poll every 30 seconds

          while true; do
            CURRENT_TIME=$(date +%s000)
            LOGS=$(aws logs filter-log-events \
              --log-group-name $LOG_GROUP_NAME \
              --start-time $START_TIME \
              --query "events[?contains(message, \`$COMPLETION_MESSAGE\`) == \`true\`].message" \
              --region eu-north-1 \
              --output text)

            if [[ -n "$LOGS" ]]; then
              echo "Upsert Lambda completed successfully."
              break
            fi

            ELAPSED=$((CURRENT_TIME / 1000 - START_TIME / 1000))
            if [[ $ELAPSED -ge $TIMEOUT ]]; then
              echo "Timeout reached while waiting for upsert Lambda to complete."
              exit 1
            fi

            echo "Waiting for upsert Lambda to complete..."
            sleep $POLL_INTERVAL
          done

      # Step 3: Trigger dbt Cloud job and wait for completion
      - name: Trigger dbt Cloud job and wait
        id: trigger_dbt_job
        env:
          DBT_API_KEY: ${{ secrets.DBT_API_KEY }}
        run: |
          JOB_ID=70471823414370
          echo "Triggering dbt Cloud job..."
          RESPONSE=$(curl -X POST "https://cloud.getdbt.com/api/v2/accounts/70471823412077/jobs/$JOB_ID/run/" \
            -H "Authorization: Bearer $DBT_API_KEY" \
            -H "Content-Type: application/json")
          RUN_ID=$(echo "$RESPONSE" | jq -r '.data.id')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Triggered dbt job with Run ID: $RUN_ID"

          echo "Waiting for dbt Cloud job to complete..."
          STATUS="running"
          while [[ "$STATUS" == "running" || "$STATUS" == "queued" ]]; do
            sleep 30
            STATUS=$(curl -X GET "https://cloud.getdbt.com/api/v2/accounts/70471823412077/runs/$RUN_ID/" \
              -H "Authorization: Bearer $DBT_API_KEY" \
              -H "Content-Type: application/json" | jq -r '.data.status_humanized' | tr '[:upper:]' '[:lower:]')
            echo "Current job status: $STATUS"
          done

          if [[ "$STATUS" == "success" ]]; then
            echo "dbt Cloud job completed successfully."
          else
            echo "dbt Cloud job failed with status: $STATUS"
            exit 1
          fi

      # Step 4: Redeploy Vercel deployment
      - name: Redeploy on Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          curl -X POST "https://api.vercel.com/v13/deployments/{deployment_id}/retrigger" \
            -H "Authorization: Bearer $VERCEL_TOKEN"
